GET http://localhost:8081/api/event/EB3444FB3A9F183C0/get/

###
GET http://localhost:8081/api/events/get/

###
POST http://localhost:8081/api/login/
content-type: application/json

{
    "auth": {
        "username": "FelixNPL",
        "password": "20151529"
    }
}

###

GET http://localhost:8081/api/shutdown/

###

POST http://localhost:8081/api/register/
content-type: application/json

{
    "register": {
        "username": "FelixNPL",
        "display_name": "Felix NPL",
        "email": "user00000@test.com",
        "password": "20151529",
        "first_name": "Felix",
        "last_name": "NPL",
        "access_level": "participator"
    }
}

