GET http://localhost:8081/api/event/EB3444FB3A9F183C0/get/

###

POST http://localhost:8081/api/login/
content-type: application/json

{
    "auth": {
        "username": "FelixNPL",
        "password": "20151529"
    }
}

###

GET http://localhost:8081/api/shutdown/